#!/usr/bin/env python

from werkzeug.serving import run_simple

from pod_manager.api.handlers import API

if __name__ == '__main__':
    app = API()
    run_simple('127.0.0.1', 8000, app, use_debugger=True, use_reloader=True)
